import 'package:flutter/material.dart';
import 'package:munasabati/models/booking_models.dart';

// Demo data for UI development

final List<ServiceModel> demoHalls = [
  ServiceModel(
    id: 'hall-1',
    providerId: 'prov-1',
    title: 'Grand Ballroom Palace',
    description:
        'Luxurious ballroom with crystal chandeliers, marble floors, and a grand stage. Perfect for weddings and large celebrations.',
    serviceType: ServiceType.hall,
    basePrice: 5000,
    currency: 'USD',
    pricingModel: PricingModel.perEvent,
    images: [
      'https://images.unsplash.com/photo-1519167758481-83f550bb2e78?w=800',
      'https://images.unsplash.com/photo-1464366401160-687b903e1e3a?w=800',
      'https://images.unsplash.com/photo-1478146059778-26028b3c2875?w=800',
    ],
    tags: ['luxury', 'ballroom', 'wedding', 'indoor'],
    attributes: const ServiceAttributes(
      capacity: 500,
      hasStage: true,
      hasParking: true,
      hasKitchen: true,
      theme: 'Classic Elegance',
      amenities: [
        'Stage',
        'Sound System',
        'Lighting',
        'Kitchen',
        'Parking',
        'Bridal Suite'
      ],
    ),
    maxCapacity: 500,
    minDurationHours: 4,
    maxDurationHours: 12,
    provider: ProviderModel(
      id: 'prov-1',
      userId: 'user-1',
      businessName: 'Royal Venues Inc.',
      serviceType: ServiceType.hall,
      rating: 4.8,
      reviewCount: 124,
      isVerified: true,
      city: 'New York',
      country: 'USA',
    ),
  ),
  ServiceModel(
    id: 'hall-2',
    providerId: 'prov-2',
    title: 'Garden Oasis Pavilion',
    description:
        'Beautiful outdoor garden venue with a covered pavilion, string lights, and lush greenery. Ideal for romantic weddings.',
    serviceType: ServiceType.hall,
    basePrice: 3500,
    currency: 'USD',
    pricingModel: PricingModel.perEvent,
    images: [
      'https://images.unsplash.com/photo-1464366401160-687b903e1e3a?w=800',
      'https://images.unsplash.com/photo-1510076857177-7e0c870a762e?w=800',
    ],
    tags: ['garden', 'outdoor', 'romantic', 'pavilion'],
    attributes: const ServiceAttributes(
      capacity: 200,
      hasStage: true,
      hasParking: true,
      hasKitchen: false,
      theme: 'Rustic Garden',
      amenities: ['Pavilion', 'Garden', 'String Lights', 'Parking'],
    ),
    maxCapacity: 200,
    minDurationHours: 4,
    maxDurationHours: 10,
    provider: ProviderModel(
      id: 'prov-2',
      userId: 'user-2',
      businessName: 'Green Garden Venues',
      serviceType: ServiceType.hall,
      rating: 4.5,
      reviewCount: 67,
      isVerified: true,
      city: 'Los Angeles',
      country: 'USA',
    ),
  ),
  ServiceModel(
    id: 'hall-3',
    providerId: 'prov-3',
    title: 'Modern Loft Studio',
    description:
        'Industrial-chic loft space with exposed brick, high ceilings, and modern lighting. Great for intimate events.',
    serviceType: ServiceType.hall,
    basePrice: 2000,
    currency: 'USD',
    pricingModel: PricingModel.hourly,
    images: [
      'https://images.unsplash.com/photo-1478146059778-26028b3c2875?w=800',
    ],
    tags: ['modern', 'loft', 'industrial', 'intimate'],
    attributes: const ServiceAttributes(
      capacity: 100,
      hasStage: false,
      hasParking: true,
      hasKitchen: true,
      theme: 'Modern Industrial',
      amenities: ['Kitchen', 'Parking', 'Sound System', 'Projector'],
    ),
    maxCapacity: 100,
    minDurationHours: 2,
    maxDurationHours: 8,
    provider: ProviderModel(
      id: 'prov-3',
      userId: 'user-3',
      businessName: 'Urban Spaces Co.',
      serviceType: ServiceType.hall,
      rating: 4.3,
      reviewCount: 45,
      isVerified: true,
      city: 'Chicago',
      country: 'USA',
    ),
  ),
];

final List<ServiceModel> demoCars = [
  ServiceModel(
    id: 'car-1',
    providerId: 'prov-4',
    title: 'Vintage Rolls Royce Silver Shadow',
    description:
        'Classic 1965 Rolls Royce in pristine condition. Perfect for the bride\'s grand entrance.',
    serviceType: ServiceType.car,
    basePrice: 800,
    currency: 'USD',
    pricingModel: PricingModel.flat,
    images: [
      'https://images.unsplash.com/photo-1563727856580-9a4a0b29206b?w=800',
    ],
    tags: ['vintage', 'luxury', 'rolls-royce', 'classic'],
    attributes: const ServiceAttributes(
      make: 'Rolls Royce',
      model: 'Silver Shadow',
      year: 1965,
      color: 'Silver',
      carType: 'Vintage Luxury',
      maxPassengers: 4,
      features: ['Chauffeur', 'Champagne', 'Ribbons', 'Red Carpet'],
    ),
    minDurationHours: 3,
    maxDurationHours: 12,
    provider: ProviderModel(
      id: 'prov-4',
      userId: 'user-4',
      businessName: 'Elite Wedding Cars',
      serviceType: ServiceType.car,
      rating: 4.9,
      reviewCount: 89,
      isVerified: true,
      city: 'New York',
      country: 'USA',
    ),
  ),
  ServiceModel(
    id: 'car-2',
    providerId: 'prov-5',
    title: 'White Mercedes-Benz S-Class Limo',
    description:
        'Elegant white stretch limousine with premium interior. Accommodates the entire wedding party.',
    serviceType: ServiceType.car,
    basePrice: 1200,
    currency: 'USD',
    pricingModel: PricingModel.hourly,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800',
    ],
    tags: ['limousine', 'white', 'mercedes', 'party'],
    attributes: const ServiceAttributes(
      make: 'Mercedes-Benz',
      model: 'S-Class Limo',
      year: 2023,
      color: 'White',
      carType: 'Limousine',
      maxPassengers: 12,
      features: ['Bar', 'LED Lighting', 'Sound System', 'Privacy Partition'],
    ),
    minDurationHours: 2,
    maxDurationHours: 10,
    provider: ProviderModel(
      id: 'prov-5',
      userId: 'user-5',
      businessName: 'Luxury Limo Services',
      serviceType: ServiceType.car,
      rating: 4.7,
      reviewCount: 56,
      isVerified: true,
      city: 'Miami',
      country: 'USA',
    ),
  ),
  ServiceModel(
    id: 'car-3',
    providerId: 'prov-6',
    title: 'ClassicConvertible Mustang',
    description:
        'Iconic Ford Mustang convertible for a stylish getaway car. Available in red or white.',
    serviceType: ServiceType.car,
    basePrice: 500,
    currency: 'USD',
    pricingModel: PricingModel.flat,
    images: [],
    tags: ['convertible', 'mustang', 'sporty', 'getaway'],
    attributes: const ServiceAttributes(
      make: 'Ford',
      model: 'Mustang Convertible',
      year: 2020,
      color: 'Red',
      carType: 'Sports Convertible',
      maxPassengers: 2,
      features: ['Convertible Top', 'Sport Mode', 'Ribbons'],
    ),
    minDurationHours: 2,
    maxDurationHours: 6,
    provider: ProviderModel(
      id: 'prov-6',
      userId: 'user-6',
      businessName: 'Sport Car Rentals',
      serviceType: ServiceType.car,
      rating: 4.4,
      reviewCount: 32,
      isVerified: false,
      city: 'Las Vegas',
      country: 'USA',
    ),
  ),
];

final List<ServiceModel> demoPhotographers = [
  ServiceModel(
    id: 'photo-1',
    providerId: 'prov-7',
    title: 'Dream Lens Photography',
    description:
        'Award-winning wedding photography with a cinematic style. Full day coverage with editing included.',
    serviceType: ServiceType.photographer,
    basePrice: 3000,
    currency: 'USD',
    pricingModel: PricingModel.perEvent,
    images: [
      'https://images.unsplash.com/photo-1537633557785-4fb3a7c6150f?w=800',
    ],
    tags: ['cinematic', 'award-winning', 'wedding', 'premium'],
    attributes: const ServiceAttributes(
      portfolioUrl: 'https://dreamlens.example.com',
      specialties: ['Wedding', 'Portrait', 'Cinematic'],
      equipment: ['Canon R5', 'Sony A7IV', 'DJI Mavic 3'],
      editingIncluded: true,
    ),
    minDurationHours: 4,
    maxDurationHours: 12,
    provider: ProviderModel(
      id: 'prov-7',
      userId: 'user-7',
      businessName: 'Dream Lens Studio',
      serviceType: ServiceType.photographer,
      rating: 4.9,
      reviewCount: 201,
      isVerified: true,
      city: 'New York',
      country: 'USA',
    ),
  ),
  ServiceModel(
    id: 'photo-2',
    providerId: 'prov-8',
    title: 'Golden Hour Studios',
    description:
        'Natural light specialist focusing on candid moments and golden hour magic. Half and full day packages.',
    serviceType: ServiceType.photographer,
    basePrice: 1800,
    currency: 'USD',
    pricingModel: PricingModel.perEvent,
    images: [],
    tags: ['natural', 'candid', 'golden-hour', 'affordable'],
    attributes: const ServiceAttributes(
      specialties: ['Candid', 'Natural Light', 'Golden Hour'],
      equipment: ['Nikon Z9', 'Sigma Art Lenses'],
      editingIncluded: true,
    ),
    minDurationHours: 3,
    maxDurationHours: 10,
    provider: ProviderModel(
      id: 'prov-8',
      userId: 'user-8',
      businessName: 'Golden Hour Studios',
      serviceType: ServiceType.photographer,
      rating: 4.6,
      reviewCount: 88,
      isVerified: true,
      city: 'San Francisco',
      country: 'USA',
    ),
  ),
];

final List<ServiceModel> demoEntertainers = [
  ServiceModel(
    id: 'ent-1',
    providerId: 'prov-9',
    title: 'Melody Makers Live Band',
    description:
        '5-piece live band covering top hits from all decades. High-energy performance guaranteed.',
    serviceType: ServiceType.entertainer,
    basePrice: 4000,
    currency: 'USD',
    pricingModel: PricingModel.perEvent,
    images: [
      'https://images.unsplash.com/photo-1514320291840-2e0a9bf206a8?w=800',
    ],
    tags: ['live-band', 'party', 'high-energy', 'covers'],
    attributes: const ServiceAttributes(
      performerType: 'Live Band',
      genres: ['Pop', 'Rock', 'R&B', 'Jazz'],
      groupSize: 5,
    ),
    minDurationHours: 2,
    maxDurationHours: 6,
    provider: ProviderModel(
      id: 'prov-9',
      userId: 'user-9',
      businessName: 'Melody Makers Entertainment',
      serviceType: ServiceType.entertainer,
      rating: 4.8,
      reviewCount: 156,
      isVerified: true,
      city: 'Nashville',
      country: 'USA',
    ),
  ),
  ServiceModel(
    id: 'ent-2',
    providerId: 'prov-10',
    title: 'DJ Harmony',
    description:
        'Professional DJ with state-of-the-art sound and lighting. Specializes in wedding receptions.',
    serviceType: ServiceType.entertainer,
    basePrice: 1500,
    currency: 'USD',
    pricingModel: PricingModel.hourly,
    images: [],
    tags: ['dj', 'wedding', 'reception', 'lighting'],
    attributes: const ServiceAttributes(
      performerType: 'DJ',
      genres: ['EDM', 'Pop', 'Hip-Hop', 'Arabic', 'International'],
      groupSize: 1,
    ),
    minDurationHours: 3,
    maxDurationHours: 8,
    provider: ProviderModel(
      id: 'prov-10',
      userId: 'user-10',
      businessName: 'DJ Harmony Events',
      serviceType: ServiceType.entertainer,
      rating: 4.7,
      reviewCount: 93,
      isVerified: true,
      city: 'Miami',
      country: 'USA',
    ),
  ),
  ServiceModel(
    id: 'ent-3',
    providerId: 'prov-11',
    title: 'Soprano Serena - Wedding Singer',
    description:
        'Classically trained soprano for ceremony music. Repertoire includes traditional and modern wedding songs.',
    serviceType: ServiceType.entertainer,
    basePrice: 1200,
    currency: 'USD',
    pricingModel: PricingModel.flat,
    images: [],
    tags: ['singer', 'soprano', 'ceremony', 'classical'],
    attributes: const ServiceAttributes(
      performerType: 'Solo Singer',
      genres: ['Classical', 'Opera', 'Contemporary', 'Traditional'],
      groupSize: 1,
    ),
    minDurationHours: 1,
    maxDurationHours: 4,
    provider: ProviderModel(
      id: 'prov-11',
      userId: 'user-11',
      businessName: 'Serena Music',
      serviceType: ServiceType.entertainer,
      rating: 4.9,
      reviewCount: 47,
      isVerified: true,
      city: 'Boston',
      country: 'USA',
    ),
  ),
];

List<ServiceModel> get allDemoServices =>
    [...demoHalls, ...demoCars, ...demoPhotographers, ...demoEntertainers];

List<ServiceModel> getServicesByType(ServiceType type) {
  switch (type) {
    case ServiceType.hall:
      return demoHalls;
    case ServiceType.car:
      return demoCars;
    case ServiceType.photographer:
      return demoPhotographers;
    case ServiceType.entertainer:
      return demoEntertainers;
  }
}

final List<BookingModel> demoBookings = [
  BookingModel(
    id: 'booking-1',
    consumerId: 'user-consumer-1',
    eventType: 'wedding',
    eventDate: DateTime(2025, 6, 15),
    eventName: 'Sarah & James Wedding',
    status: BookingStatus.confirmed,
    totalAmount: 12800,
    depositAmount: 3200,
    depositPaid: true,
    items: [
      BookingItem(
        id: 'item-1',
        bookingId: 'booking-1',
        serviceId: 'hall-1',
        providerId: 'prov-1',
        date: DateTime(2025, 6, 15),
        startTime: TimeOfDay(hour: 16, minute: 0),
        endTime: TimeOfDay(hour: 23, minute: 0),
        durationHours: 7,
        unitPrice: 5000,
        subtotal: 5000,
        status: BookingStatus.confirmed,
        service: demoHalls[0],
        provider: demoHalls[0].provider,
      ),
      BookingItem(
        id: 'item-2',
        bookingId: 'booking-1',
        serviceId: 'car-1',
        providerId: 'prov-4',
        date: DateTime(2025, 6, 15),
        startTime: TimeOfDay(hour: 15, minute: 0),
        endTime: TimeOfDay(hour: 18, minute: 0),
        durationHours: 3,
        unitPrice: 800,
        subtotal: 800,
        status: BookingStatus.confirmed,
        service: demoCars[0],
        provider: demoCars[0].provider,
      ),
      BookingItem(
        id: 'item-3',
        bookingId: 'booking-1',
        serviceId: 'photo-1',
        providerId: 'prov-7',
        date: DateTime(2025, 6, 15),
        startTime: TimeOfDay(hour: 14, minute: 0),
        endTime: TimeOfDay(hour: 22, minute: 0),
        durationHours: 8,
        unitPrice: 3000,
        subtotal: 3000,
        status: BookingStatus.confirmed,
        service: demoPhotographers[0],
        provider: demoPhotographers[0].provider,
      ),
      BookingItem(
        id: 'item-4',
        bookingId: 'booking-1',
        serviceId: 'ent-1',
        providerId: 'prov-9',
        date: DateTime(2025, 6, 15),
        startTime: TimeOfDay(hour: 19, minute: 0),
        endTime: TimeOfDay(hour: 23, minute: 0),
        durationHours: 4,
        unitPrice: 4000,
        subtotal: 4000,
        status: BookingStatus.confirmed,
        service: demoEntertainers[0],
        provider: demoEntertainers[0].provider,
      ),
    ],
  ),
  BookingModel(
    id: 'booking-2',
    consumerId: 'user-consumer-1',
    eventType: 'birthday',
    eventDate: DateTime(2025, 7, 20),
    eventName: 'Mom\'s 50th Birthday',
    status: BookingStatus.pending,
    totalAmount: 5500,
    depositAmount: 1375,
    depositPaid: false,
    items: [
      BookingItem(
        id: 'item-5',
        bookingId: 'booking-2',
        serviceId: 'hall-2',
        providerId: 'prov-2',
        date: DateTime(2025, 7, 20),
        startTime: TimeOfDay(hour: 18, minute: 0),
        endTime: TimeOfDay(hour: 22, minute: 0),
        durationHours: 4,
        unitPrice: 3500,
        subtotal: 3500,
        status: BookingStatus.pending,
        service: demoHalls[1],
        provider: demoHalls[1].provider,
      ),
      BookingItem(
        id: 'item-6',
        bookingId: 'booking-2',
        serviceId: 'ent-2',
        providerId: 'prov-10',
        date: DateTime(2025, 7, 20),
        startTime: TimeOfDay(hour: 19, minute: 0),
        endTime: TimeOfDay(hour: 23, minute: 0),
        durationHours: 4,
        unitPrice: 1500,
        subtotal: 2000,
        status: BookingStatus.pending,
        service: demoEntertainers[1],
        provider: demoEntertainers[1].provider,
      ),
    ],
  ),
];
